meta_product_name: "Halfway"
meta_title: "Halfway - Making meeting up easier."
meta_description: "Halfway recommends restaurants, bars and cafes at the halfway point between you and your friend's location. It is perfect for young, sociable professionals leading busy lives in London."
meta_image: "../../app/assets/images/home3.png" # should exist in `app/assets/images/`
